apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-one
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-1
        configMap:
          name: configmap-one

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-2
        configMap:
          name: configmap-two


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-three
  namespace: demo
spec:
  replicas: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-1
        configMap:
          name: configmap-three