apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-three
  namespace: demo
data:
  index.html: |
    <html>
    <head><title>Level Up!</title></head>
    <body/>
    <h1>This is Deployment Three.</h1>
    </body></html>
  
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-three
  namespace: demo
spec:
  replicas: 
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx3
        image: nginx3
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-3
          mountPath: /usr/share/nginx/html/three
      volumes:
      - name: config-3
        configMap:
          name: configmap-three

---

apiVersion: v1
kind: Service
metadata:
  name: nginx3service
  namespace: demo
  labels :
    app: nginx3
spec:
  type: ClusterIP
  selector:
    app: nginx3
  ports:
    - name: myservice3
      protocol: TCP
      port: 80
      targetPort: 80