apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-three
  namespace: demo
data:
  index.html: |
    <html>
    <head><title>Level Up!</title></head>
    <body/>
    <h1>This is Deployment Three.</h1>
    </body></html>
  
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-three
  namespace: demo
spec:
  replicas: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
          - containerPort: 90
        volumeMounts:
        - name: config-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-1
        configMap:
          name: configmap-three

---

apiVersion: v1
kind: Service
metadata:
  name: nginx3service
  namespace: demo
  labels :
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: myservice3
      protocol: TCP
      port: 9090
      targetPort: 90