apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-one
  namespace: namespace1
data:
  index.html: |
    <html>
    <head><title>Level Up!</title></head>
    <body/>
    <h1>This is Deployment One.</h1>
    </body></html>
  
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-one
  namespace: namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-1
        configMap:
          name: configmap-one

---

apiVersion: v1
kind: Service
metadata:
  name: nginx1service
  namespace: namespace1
  labels :
    app: nginx1
spec:
  type: ClusterIP
  selector:
    app: nginx1
  ports:
    - name: myservice1
      protocol: TCP
      port: 80