apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx
  namespace: demo
spec:
  parentRefs:
  - name: example-gateway
    kind: Gateway
  hostnames:
  - "nginxservice1.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nginx1service
    backendRefs:
    - name: nginx1service.demo.svc.cluster.local
      kind: Service
      port: 80
  hostnames:
  - "nginxservice2.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nginx2service
    backendRefs:
    - name: nginx2service.demo.svc.cluster.local
      port: 80
  hostnames:
  - "nginxservice3.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nginx3service
    backendRefs:
    - name: nginx3service.demo.svc.cluster.local
      kind: Service
      port: 80