apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: demo
spec:
  rules:
  - host: "nginx-service1.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx1-service.demo.svc.cluster.local
            port:
              number: 80
  - host: "nginx-service2.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx2-service.demo.svc.cluster.local
            port:
              number: 80
    - host: "nginx-service3.com"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: nginx3-service.demo.svc.cluster.local
              port:
                number: 80